#!/bin/sh
set -eu

if [ $# -lt 1 ]; then
  echo 'No task is specified.' >&2
  exit 1
fi

cd $(dirname $0)

case $1 in
  'init-vcpkg' )
    cd vcpkg
    ./bootstrap-vcpkg.sh
    ./vcpkg remove --outdated --recurse
    ./vcpkg install boost-filesystem boost-program-options boost-serialization ceres double-conversion eigen3 flann gtest --triplet x64-linux
    ;;
  'cmake' )
    mkdir -p build
    cd build
    cmake .. -GNinja -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=../vcpkg/scripts/buildsystems/vcpkg.cmake
    ;;
  'b'|'build' )
    cd build
    ninja
    ;;
  't'|'test' )
    cd build
    ctest -V
    ;;
  * )
    echo "Unrecognized task: $1" >&2
    exit 1
    ;;
esac
