#!/bin/sh

cd $(dirname $0)/../..

! find benchmark/ examples/ include/ src/ test/ '(' \
    -name '*.cpp' -or \
    -name '*.hpp' \
  ')' -and -not '(' \
    -path 'include/polatory/third_party/*' -or \
    -path 'src/third_party/*' \
  ')' \
  | xargs python tools/inspection/cpplint/cpplint.py --filter=-runtime/int,-runtime/references,-whitespace/braces,-whitespace/comments,-whitespace/indent,-whitespace/line_length,-whitespace/parens 2>&1 \
  | grep -v '^Done processing '
