#!/bin/sh

case "$(uname)" in
  Linux )
    echo ''
    ;;
  Darwin )
    echo -DCMAKE_CXX_COMPILER="$(brew --prefix)/opt/llvm/bin/clang++"
    ;;
  * )
    echo 'Unsupported operating system' >&2
    exit 1
    ;;
esac
