#!/bin/sh

case "$(uname)" in
  Linux )
    echo ''
    ;;
  Darwin )
    if [ "$CI" ]; then
      echo -DCMAKE_CXX_COMPILER="$(brew --prefix llvm@15)/bin/clang++"
    else
      echo -DCMAKE_CXX_COMPILER="$(brew --prefix)/opt/llvm/bin/clang++"
    fi
    ;;
  * )
    echo 'Unsupported operating system' >&2
    exit 1
    ;;
esac
