#!/bin/sh

case "$(uname -s)" in
  Linux )
    echo ''
    ;;
  Darwin )
    echo "$(brew --prefix)/opt/llvm/bin/clang++"
    ;;
  * )
    echo 'Unsupported operating system' >&2
    exit 1
    ;;
esac
