#!/bin/sh

case "$(uname -s)" in
  Linux )
    case "$(uname -m)" in
      x86_64 )
        echo x64-linux
        ;;
      * )
        echo 'Unsupported architecture' >&2
        exit 1
        ;;
    esac
    ;;
  Darwin )
    case "$(uname -m)" in
      x86_64 )
        echo x64-osx
        ;;
      arm64 )
        echo arm64-osx
        ;;
      * )
        echo 'Unsupported architecture' >&2
        exit 1
        ;;
    esac
    ;;
  * )
    echo 'Unsupported operating system' >&2
    exit 1
    ;;
esac
